<p style="color: blue; font-size: 30px;">
Devoir
    
</p>

In [1]:
import numpy as np

grille = np.array([
    [0, 0, 0, 0, 0],
    [0, 1, 0, 1, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 0, 0, 2]
])

lignes, colonnes = grille.shape
directions = ['HAUT', 'BAS', 'GAUCHE', 'DROITE']

def recompense(x, y):
    if grille[x, y] == 1:
        return -10
    elif grille[x, y] == 2:
        return 10
    else:
        return -1

def afficher(position):
    grille_affichage = grille.copy()
    x, y = position
    grille_affichage[x, y] = 3
    print(grille_affichage)
    print("-" * 20)

def chemin():
    x, y = 0, 0
    chemin = [(x, y)]
   
    while grille[x, y] != 2:
        if y < colonnes - 1 and grille[x, y + 1] != 1:
            y += 1
        elif x < lignes - 1 and grille[x + 1, y] != 1:
            x += 1 
        else:
            print("L'agent est bloque ")
            break
        
        chemin.append((x, y))
        afficher((x, y))
        
        if grille[x, y] == 2:
            print("L'agent a trouve le tresor")
    
    print("Chemin suivi :")
    for i in chemin:
        print(i)

chemin()


[[0 3 0 0 0]
 [0 1 0 1 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 2]]
--------------------
[[0 0 3 0 0]
 [0 1 0 1 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 2]]
--------------------
[[0 0 0 3 0]
 [0 1 0 1 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 2]]
--------------------
[[0 0 0 0 3]
 [0 1 0 1 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 2]]
--------------------
[[0 0 0 0 0]
 [0 1 0 1 3]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 2]]
--------------------
[[0 0 0 0 0]
 [0 1 0 1 0]
 [0 0 0 0 3]
 [0 0 1 0 0]
 [0 0 0 0 2]]
--------------------
[[0 0 0 0 0]
 [0 1 0 1 0]
 [0 0 0 0 0]
 [0 0 1 0 3]
 [0 0 0 0 2]]
--------------------
[[0 0 0 0 0]
 [0 1 0 1 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 3]]
--------------------
L'agent a trouve le tresor
Chemin suivi :
(0, 0)
(0, 1)
(0, 2)
(0, 3)
(0, 4)
(1, 4)
(2, 4)
(3, 4)
(4, 4)
