<p style="color: blue; font-size: 30px;">
 la solution de l'exercice 1
</p>

In [1]:
import gymnasium as gym  

env = gym.make("FrozenLake-v1", render_mode="human")  
observation, _ = env.reset()

print(f"Espaces d'actions : {env.action_space}")
print(f"Espaces d'observation: {env.observation_space}")

for _ in range(100):  
    action = env.action_space.sample()  
    observation, reward, done, _, _ = env.step(action)  

    print(f"Action : {action}, Observation : {observation}, Reward : {reward}")  

    if done:  
        observation, _ = env.reset()  

env.close()


Espaces d'actions : Discrete(4)
Espaces d'observation: Discrete(16)
Action : 1, Observation : 0, Reward : 0.0
Action : 0, Observation : 0, Reward : 0.0
Action : 3, Observation : 0, Reward : 0.0
Action : 1, Observation : 0, Reward : 0.0
Action : 0, Observation : 0, Reward : 0.0
Action : 2, Observation : 4, Reward : 0.0
Action : 0, Observation : 8, Reward : 0.0
Action : 3, Observation : 9, Reward : 0.0
Action : 0, Observation : 5, Reward : 0.0
Action : 2, Observation : 4, Reward : 0.0
Action : 0, Observation : 4, Reward : 0.0
Action : 0, Observation : 0, Reward : 0.0
Action : 3, Observation : 0, Reward : 0.0
Action : 1, Observation : 1, Reward : 0.0
Action : 3, Observation : 2, Reward : 0.0
Action : 2, Observation : 2, Reward : 0.0
Action : 1, Observation : 3, Reward : 0.0
Action : 2, Observation : 7, Reward : 0.0
Action : 1, Observation : 0, Reward : 0.0
Action : 1, Observation : 1, Reward : 0.0
Action : 3, Observation : 0, Reward : 0.0
Action : 3, Observation : 0, Reward : 0.0
Action :

<p style="color: blue; font-size: 30px;">
 la solution de l'exercice 2
</p>

In [2]:
import gymnasium as gym  
import numpy as np

env = gym.make("FrozenLake-v1", render_mode="human")  
observation, _ = env.reset()

print(f"Espaces d'actions : {env.action_space}")
print(f"Espaces d'observation: {env.observation_space}")

for _ in range(100):  
    action = env.action_space.sample()  
    observation, reward, done, _, _ = env.step(action)  

    print(f"Action : {action}, Observation : {observation}, Reward : {reward}")  

    if done:  
        observation, _ = env.reset()  

env.close()

Q_table = np.zeros((16, 4))  # 16 états, 4 actions
print("Q-table initialization :")
print(Q_table)




Espaces d'actions : Discrete(4)
Espaces d'observation: Discrete(16)
Action : 3, Observation : 0, Reward : 0.0
Action : 1, Observation : 4, Reward : 0.0
Action : 1, Observation : 8, Reward : 0.0
Action : 2, Observation : 12, Reward : 0.0
Action : 2, Observation : 1, Reward : 0.0
Action : 0, Observation : 5, Reward : 0.0
Action : 0, Observation : 4, Reward : 0.0
Action : 1, Observation : 5, Reward : 0.0
Action : 3, Observation : 0, Reward : 0.0
Action : 3, Observation : 0, Reward : 0.0
Action : 1, Observation : 4, Reward : 0.0
Action : 2, Observation : 5, Reward : 0.0
Action : 1, Observation : 0, Reward : 0.0
Action : 1, Observation : 1, Reward : 0.0
Action : 1, Observation : 5, Reward : 0.0
Action : 2, Observation : 0, Reward : 0.0
Action : 0, Observation : 0, Reward : 0.0
Action : 2, Observation : 0, Reward : 0.0
Action : 2, Observation : 1, Reward : 0.0
Action : 2, Observation : 1, Reward : 0.0
Action : 3, Observation : 0, Reward : 0.0
Action : 3, Observation : 0, Reward : 0.0
Action 

<p style="color: blue; font-size: 30px;">
 la solution de l'exercice 3et 4
</p>

In [ ]:
import gymnasium as gym  
import numpy as np
env = gym.make("FrozenLake-v1", render_mode="human") 
observation, _ = env.reset()

print(f"Espaces d'actions : {env.action_space}")
print(f"Espaces d'observation: {env.observation_space}")

Q_table = np.zeros((16, 4))  
print("Q-table initialization :")
print(Q_table)


alpha = 0.1        # Learning rate
gamma = 0.99       # Discount factor
epsilon = 1.0      # Initial exploration rate 
epsilon_decay = 0.995  # Facteur de réduction d'epsilon
epsilon_min = 0.01  # Valeur minimale d'epsilon
num_episodes = 5000  # Nombre total d'épisodes

for episode in range(num_episodes):
    state, _ = env.reset()
    done = False
    
    while not done:
    
        if np.random.rand() < epsilon:
            action = env.action_space.sample()  # Exploration
        else:
            action = np.argmax(Q_table[state, :])  # Exploitation
        
        next_state, reward, done, _, _ = env.step(action)

        Q_table[state, action] = Q_table[state, action] + alpha * (
            reward + gamma * np.max(Q_table[next_state, :]) - Q_table[state, action]
        )

        state = next_state

    epsilon = max(epsilon * epsilon_decay, epsilon_min)

    if (episode + 1) % 500 == 0:
        print(f"Episode {episode + 1}, Epsilon: {epsilon:.4f}")

print("Q-table après entraînement :")
print(Q_table)

env.close()


num_test_episodes = 100  
success_count = 0 

for episode in range(num_test_episodes):
    state, _ = env.reset()  
    done = False

    while not done:
        action = np.argmax(Q_table[state, :])  
        next_state, reward, done, _, _ = env.step(action)  
        state = next_state

        if reward == 1: 
            success_count += 1


success_rate = success_count / num_test_episodes * 100
print(f"Succès sur {num_test_episodes} épisodes : {success_count}")
print(f"Taux de réussite : {success_rate:.2f}%")


Espaces d'actions : Discrete(4)
Espaces d'observation: Discrete(16)
Q-table initialization :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Episode 500, Epsilon: 0.0816
